server:
  port: 7070
  servlet:
    context-path: /product-service
spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: product-service


