# 当前工程端口的配置
server:
  port: 8081
  servlet:
    context-path: /demo


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    max-channel: 64


